# Generated by Django 4.2.13 on 2025-10-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
