# Generated by Django 4.2.13 on 2025-10-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('ENT', 'ENT'), ('Neurology', 'Neurology')], max_length=20, null=True),
        ),
    ]
