# Generated by Django 4.2.13 on 2025-10-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_staff_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_plan',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_valid_to',
        ),
    ]
