# Generated by Django 4.2.13 on 2025-10-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_patient_insurance_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancepolicy',
            old_name='company_name',
            new_name='company_and_policy_name',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='policy_name',
        ),
    ]
