# Generated by Django 4.2.13 on 2025-10-30 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_rename_company_name_insurancepolicy_company_and_policy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(default="No notes yet"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(default="No notes yet"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(default="No notes yet"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default="No notes yet"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(default="No notes yet", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(default="No notes yet", max_length=100),
            preserve_default=False,
        ),
    ]
